# Gets the league
GET http://localhost:5000/league

# gets Playerscore
GET http://localhost:5000/players/Pepper

# gets Playerscore Not found
GET http://localhost:5000/players/missing

# post a win for pepper
POST http://localhost:5000/players/Pepper
